import { missingLang } from "../notification";

// ISO 639-1
const languages: Language[] = [
    { name: "Абхазский", code: "ab" },
    { name: "Аварский", code: "av" },
    { name: "Авестийский", code: "ae" },
    { name: "Азербайджанский", code: "az" },
    { name: "Аймара", code: "ay" },
    { name: "Акан", code: "ak" },
    { name: "Албанский", code: "sq" },
    { name: "Амхарский", code: "am" },
    { name: "Английский", code: "en" },
    { name: "Арабский", code: "ar" },
    { name: "Армянский", code: "hy" },
    { name: "Ассамский", code: "as" },
    { name: "Афарский", code: "aa" },
    { name: "Африкаанс", code: "af" },
    { name: "Бамбара", code: "bm" },
    { name: "Баскский", code: "eu" },
    { name: "Башкирский", code: "ba" },
    { name: "Белорусский", code: "be" },
    { name: "Бенгальский", code: "bn" },
    { name: "Бирманский", code: "my" },
    { name: "Бислама", code: "bi" },
    { name: "Болгарский", code: "bg" },
    { name: "Боснийский", code: "bs" },
    { name: "Бретонский", code: "br" },
    { name: "Валлийский", code: "cy" },
    { name: "Венгерский", code: "hu" },
    { name: "Венда", code: "ve" },
    { name: "Волапюк", code: "vo" },
    { name: "Волоф", code: "wo" },
    { name: "Вьетнамский", code: "vi" },
    { name: "Галисийский", code: "gl" },
    { name: "Ганда", code: "lg" },
    { name: "Гереро", code: "hz" },
    { name: "Гренландский", code: "kl" },
    { name: "Греческий (новогреческий)", code: "el" },
    { name: "Грузинский", code: "ka" },
    { name: "Гуарани", code: "gn" },
    { name: "Гуджарати", code: "gu" },
    { name: "Гэльский", code: "gd" },
    { name: "Датский", code: "da" },
    { name: "Дзонг-кэ", code: "dz" },
    { name: "Дивехи (Мальдивский)", code: "dv" },
    { name: "Зулу", code: "zu" },
    { name: "Иврит", code: "he" },
    { name: "Игбо", code: "ig" },
    { name: "Идиш", code: "yi" },
    { name: "Индонезийский", code: "id" },
    { name: "Интерлингва", code: "ia" },
    { name: "Интерлингве", code: "ie" },
    { name: "Инуктитут", code: "iu" },
    { name: "Инупиак", code: "ik" },
    { name: "Ирландский", code: "ga" },
    { name: "Исландский", code: "is" },
    { name: "Испанский", code: "es" },
    { name: "Итальянский", code: "it" },
    { name: "Йоруба", code: "yo" },
    { name: "Казахский", code: "kk" },
    { name: "Каннада", code: "kn" },
    { name: "Канури", code: "kr" },
    { name: "Каталанский", code: "ca" },
    { name: "Кашмири", code: "ks" },
    { name: "Кечуа", code: "qu" },
    { name: "Кикуйю", code: "ki" },
    { name: "Киньяма", code: "kj" },
    { name: "Киргизский", code: "ky" },
    { name: "Китайский", code: "zh" },
    { name: "Коми", code: "kv" },
    { name: "Конго", code: "kg" },
    { name: "Корейский", code: "ko" },
    { name: "Корнский", code: "kw" },
    { name: "Корсиканский", code: "co" },
    { name: "Коса", code: "xh" },
    { name: "Курдский", code: "ku" },
    { name: "Кхмерский", code: "km" },
    { name: "Лаосский", code: "lo" },
    { name: "Латинский", code: "la" },
    { name: "Латышский", code: "lv" },
    { name: "Лингала", code: "ln" },
    { name: "Литовский", code: "lt" },
    { name: "Луба-катанга", code: "lu" },
    { name: "Люксембургский", code: "lb" },
    { name: "Македонский", code: "mk" },
    { name: "Малагасийский", code: "mg" },
    { name: "Малайский", code: "ms" },
    { name: "Малаялам", code: "ml" },
    { name: "Мальтийский", code: "mt" },
    { name: "Маори", code: "mi" },
    { name: "Маратхи", code: "mr" },
    { name: "Маршалльский", code: "mh" },
    { name: "Мерянский", code: "me" },
    { name: "Молдавский", code: "mo" },
    { name: "Монгольский", code: "mn" },
    { name: "Мэнский (Мэнкский)", code: "gv" },
    { name: "Навахо", code: "nv" },
    { name: "Науру", code: "na" },
    { name: "Ндебеле северный", code: "nd" },
    { name: "Ндебеле южный", code: "nr" },
    { name: "Ндунга", code: "ng" },
    { name: "Немецкий", code: "de" },
    { name: "Непальский", code: "ne" },
    { name: "Нидерландский (Голландский)", code: "nl" },
    { name: "Норвежский", code: "no" },
    { name: "Ньянджа", code: "ny" },
    { name: "Нюнорск (новонорвежский)", code: "nn" },
    { name: "Оджибве", code: "oj" },
    { name: "Окситанский", code: "oc" },
    { name: "Ория", code: "or" },
    { name: "Оромо", code: "om" },
    { name: "Осетинский", code: "os" },
    { name: "Пали", code: "pi" },
    { name: "Пенджабский", code: "pa" },
    { name: "Персидский", code: "fa" },
    { name: "Польский", code: "pl" },
    { name: "Португальский", code: "pt" },
    { name: "Пушту", code: "ps" },
    { name: "Ретороманский", code: "rm" },
    { name: "Руанда", code: "rw" },
    { name: "Румынский", code: "ro" },
    { name: "Рунди", code: "rn" },
    { name: "Русский", code: "ru" },
    { name: "Самоанский", code: "sm" },
    { name: "Санго", code: "sg" },
    { name: "Санскрит", code: "sa" },
    { name: "Сардинский", code: "sc" },
    { name: "Свази", code: "ss" },
    { name: "Сербский", code: "sr" },
    { name: "Сингальский", code: "si" },
    { name: "Синдхи", code: "sd" },
    { name: "Словацкий", code: "sk" },
    { name: "Словенский", code: "sl" },
    { name: "Сомали", code: "so" },
    { name: "Сото южный", code: "st" },
    { name: "Суахили", code: "sw" },
    { name: "Сунданский", code: "su" },
    { name: "Тагальский", code: "tl" },
    { name: "Таджикский", code: "tg" },
    { name: "Таитянский", code: "ty" },
    { name: "Тайский", code: "th" },
    { name: "Тамильский", code: "ta" },
    { name: "Татарский", code: "tt" },
    { name: "Тви", code: "tw" },
    { name: "Телугу", code: "te" },
    { name: "Тибетский", code: "bo" },
    { name: "Тигринья", code: "ti" },
    { name: "Тонганский", code: "to" },
    { name: "Тсвана", code: "tn" },
    { name: "Тсонга", code: "ts" },
    { name: "Турецкий", code: "tr" },
    { name: "Туркменский", code: "tk" },
    { name: "Узбекский", code: "uz" },
    { name: "Уйгурский", code: "ug" },
    { name: "Украинский", code: "uk" },
    { name: "Урду", code: "ur" },
    { name: "Фарерский", code: "fo" },
    { name: "Фиджи", code: "fj" },
    { name: "Филиппинский", code: "fl" },
    { name: "Финский (Suomi)", code: "fi" },
    { name: "Французский", code: "fr" },
    { name: "Фризский", code: "fy" },
    { name: "Фулах", code: "ff" },
    { name: "Хауса", code: "ha" },
    { name: "Хинди", code: "hi" },
    { name: "Хиримоту", code: "ho" },
    { name: "Хорватский", code: "hr" },
    { name: "Церковнославянский", code: "cu" },
    { name: "Чаморро", code: "ch" },
    { name: "Чеченский", code: "ce" },
    { name: "Чешский", code: "cs" },
    { name: "Чжуанский", code: "za" },
    { name: "Чувашский", code: "cv" },
    { name: "Шведский", code: "sv" },
    { name: "Шона", code: "sn" },
    { name: "Эве", code: "ee" },
    { name: "Эсперанто", code: "eo" },
    { name: "Эстонский", code: "et" },
    { name: "Яванский", code: "jv" },
    { name: "Японский", code: "ja" }
];

function findLanguage(code: string): Language {
    const key = code.split("-")[0];
    for (const lang of languages) {
        if (lang.code === key) {
            return lang;
        };
    };
    missingLang(code);
    return { name: code, code: code };
};

export { languages, findLanguage };

export type Language = {
    name: string,
    code: string
};